// Generate RFC package bridge entrypoints for package assessor.
//
//	go run ./internal/assessor/bridgegen
//
// Or from package assessor: go generate
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

func main() {
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		fatal("runtime.Caller failed")
	}
	assessorDir := filepath.Clean(filepath.Join(filepath.Dir(thisFile), ".."))
	outPath := filepath.Join(assessorDir, "bridges_gen.go")

	var b bytes.Buffer
	b.WriteString(`// Code generated by go run ./internal/assessor/bridgegen; DO NOT EDIT.

package assessor

import (
	"context"

	"seclens/internal/assessor/rfc4035"
	"seclens/internal/assessor/rfc6376"
	"seclens/internal/assessor/rfc7208"
	"seclens/internal/assessor/rfc7489"
	"seclens/internal/assessor/rfc7505"
	"seclens/internal/assessor/rfc7672"
	"seclens/internal/assessor/rfc8460"
	"seclens/internal/assessor/rfc8461"
	"seclens/internal/report"
)

// Shared deps (adapters in adapters.go).

var (
	rfc4035Deps = rfc4035.Deps{DNS: dnssecDNS{}, Gate: stdGate{}}
	rfc6376Deps = rfc6376.Deps{DNS: txtMetaDNS{}, Gate: stdGate{}}
	rfc7208Deps = rfc7208.Deps{DNS: txtDNS{}, Gate: spfGate{}}
	rfc7489Deps = rfc7489.Deps{DNS: txtDNS{}, Gate: stdGate{}}
	rfc7672Deps = rfc7672.Deps{DNS: daneDNS{}, Gate: stdGate{}}
	rfc8460Deps = rfc8460.Deps{DNS: txtDNS{}, Gate: stdGate{}}
	rfc8461Deps = rfc8461.Deps{DNS: mtastsDNS{}, Gate: stdGate{}, IPGuard: mtastsIPGuard{}}
)

// CheckDNSSEC — RFC 4034/4035.
func CheckDNSSEC(ctx context.Context, domain string) report.DNSSECResult {
	return rfc4035.Check(ctx, rfc4035.Request{Domain: domain}, rfc4035Deps)
}

// CheckDKIM — RFC 6376. Empty mxHosts triggers MX lookup for selector heuristics.
func CheckDKIM(ctx context.Context, domain string, mxHosts []string) report.DKIMResult {
	if len(mxHosts) == 0 {
		mxs, _ := DefaultClient.LookupMX(ctx, domain)
		for _, m := range mxs {
			if m.Host != "." && m.Host != "" {
				mxHosts = append(mxHosts, m.Host)
			}
		}
	}
	return rfc6376.Check(ctx, rfc6376.Request{Domain: domain, MXHosts: mxHosts}, rfc6376Deps)
}

// CheckSPF — RFC 7208.
func CheckSPF(ctx context.Context, domain string) report.SPFResult {
	return rfc7208.Check(ctx, rfc7208.Request{Domain: domain}, rfc7208Deps)
}

// CheckDMARC — RFC 7489 (mail profile).
func CheckDMARC(ctx context.Context, domain string) report.DMARCResult {
	return rfc7489.Check(ctx, rfc7489.Request{Domain: domain, NullMXProfile: false}, rfc7489Deps)
}

// CheckDMARCForNullMX — RFC 7489 under null_mx profile (no rua/pct noise).
func CheckDMARCForNullMX(ctx context.Context, domain string) report.DMARCResult {
	return rfc7489.Check(ctx, rfc7489.Request{Domain: domain, NullMXProfile: true}, rfc7489Deps)
}

// HasNullMX — RFC 7505 presence of a 0 . RR (not full compliance).
func HasNullMX(mxs []report.MXRecord) bool {
	return rfc7505.HasNullMXRR(mxs)
}

// IsStrictNullMXSPF — SPF exactly "v=spf1 -all" (null_mx scoring).
func IsStrictNullMXSPF(raw string) bool {
	return rfc7505.IsStrictNullMXSPF(raw)
}

// CheckNullMX — RFC 7505 validation for the null_mx profile.
func CheckNullMX(mxs []report.MXRecord) report.NullMXResult {
	return rfc7505.Check(mxs)
}

// CheckDANE — RFC 7672 / 6698.
func CheckDANE(ctx context.Context, domain string, mxHosts []string) report.DANEResult {
	return rfc7672.Check(ctx, rfc7672.Request{Domain: domain, MXHosts: mxHosts}, rfc7672Deps)
}

// CheckTLSRPT — RFC 8460.
func CheckTLSRPT(ctx context.Context, domain string) report.TLSRPTResult {
	return rfc8460.Check(ctx, rfc8460.Request{Domain: domain}, rfc8460Deps)
}

// CheckMTASTS — RFC 8461.
func CheckMTASTS(ctx context.Context, domain string, mxHosts []string) report.MTASTSResult {
	return rfc8461.Check(ctx, rfc8461.Request{Domain: domain, MXHosts: mxHosts}, rfc8461Deps)
}
`)

	if err := os.WriteFile(outPath, b.Bytes(), 0o600); err != nil {
		fatal(err)
	}
	fmt.Println("wrote", outPath)
}

func fatal(v any) {
	fmt.Fprintln(os.Stderr, v)
	os.Exit(1)
}
